from .convNet import convNet
from .vgg16 import IceVGG
from .vgg16src import VGG16
from .res18 import Res18
from .resModel import resModel
from .smallNet import smallNet
from .lateralNet import lateralNet
from .fcn import fcnNet
from .outsModel import outsModel